server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;
    source_charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    # 讓 .md / .pptx / .zip 帶正確 header 並強制下載
    location ~ \.(md|pptx|zip)$ {
        add_header Content-Disposition "attachment";
        default_type application/octet-stream;
    }
}
